name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Install CocoaPods
      run: |
        gem install cocoapods
        pod install
        
    - name: Build and Test
      run: |
        xcodebuild test -workspace Theater.xcworkspace -scheme Theater -destination "platform=iOS Simulator,OS=14.0,name=iPhone SE (2nd generation)" -enableCodeCoverage YES
        
    - name: Pod Lib Lint
      run: pod lib lint --allow-warnings 