name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-14
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        
    - name: Install CocoaPods
      run: gem install cocoapods -v 1.16.2
        
    - name: Cache CocoaPods
      uses: actions/cache@v3
      with:
        path: |
          ~/.cocoapods
          Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
          
    - name: Cache Xcode Derived Data
      uses: actions/cache@v3
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-derived-data-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-derived-data-
        
    - name: Install Pods
      run: pod install
        
    - name: Build and Test
      id: test
      env:
        DEVELOPER_TEAM_ID: J5A8XNQSV9
      run: |
        xcodebuild test -workspace Theater.xcworkspace -scheme Theater -destination "platform=iOS Simulator,OS=14.0,name=iPhone SE (2nd generation)" -enableCodeCoverage YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -allowProvisioningUpdates
        
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcresult
        
    - name: Validate Podspec
      if: success()
      run: pod spec lint Theater.podspec --allow-warnings
        
    - name: Pod Lib Lint
      if: success()
      run: pod lib lint --allow-warnings 