name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        
    - name: Install CocoaPods
      run: gem install cocoapods -v 1.16.2
        
    - name: Cache CocoaPods
      uses: actions/cache@v3
      with:
        path: |
          ~/.cocoapods
          Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
        
    - name: Install Pods
      run: pod install
        
    - name: Build and Test
      run: |
        xcodebuild test -workspace Theater.xcworkspace -scheme Theater -destination "platform=iOS Simulator,OS=14.0,name=iPhone SE (2nd generation)" -enableCodeCoverage YES
        
    - name: Pod Lib Lint
      run: pod lib lint --allow-warnings 